### PR TITLE
MIDI-90: Add dashboard with velocity prompt experiments

### PR DESCRIPTION
**Pull request by roszcz**
Added a new dashboard to review ideas about controlling the velocity prediction outputs.

image

### CODE REVIEW

**Review by WojciechMat — APPROVED** [review]
Looks good and FUN! I will play with it tomorrow after I train some new model.

**Comment by SamuelJanas** [comment]
Would it be possible to upload some checkpoints to huggingface?

**Comment by roszcz** [comment]
@SamuelJanas working on it! You can also run `python train.py` - you'll get the first checkpoint pretty soon (~15minutes, 1 epoch)

**Comment by WojciechMat** [comment]
@SamuelJanas I have one model trained for 10 epochs on maestro-v1-sustain dataset on [huggingface](https://huggingface.co/wmatejuk/midi-velocity-transformer)

**Review by WojciechMat — APPROVED** [review]
Tested it, LGTM :rocket:

**Pull request merged**
